### ISSUE TITLE
watchFor() doesn't work for 'standard' IDs (<=0x7FF)

### ISSUE THREAD

**Issue by csBlueChip** [collin80/can_common#2]
This function is broken https://github.com/collin80/can_common/blob/master/src/can_common.cpp#L164 ...It sets a the filter to be STD and then immediately re-sets it to be EXT, no matter what the input value
...I suspect you intended it to work the same way as the two functions that follow.

**Comment by collin80** [comment]
It seems to work. It's coded a bit oddly compared to most other functions but, here's the idea. It calls setRXFilter with the non-mailbox specific form. So, each of the two calls sets up a different mailbox. The first call sets up a standard mailbox and the second sets up an extended mailbox. It only returns the mailbox number of the the extended one but the standard one is set up first.

**Comment by csBlueChip** [comment]
Thanks for clarifying that. Apologies for the false alarm.
I'm slowly getting my head around your approach to the problem [CAN Driver] as I want to add a bunch of extra functionality.
I do hope you receive my feedback in the spirit of appreciation for the vast amount of effort you have clearly invested in to the code you have made freely available.
